[env]
TERM = "xterm-256color"

[general]
import = ["~/.config/alacritty/themes/vague.toml"]

[window]
decorations = "None"
padding = { x = 30, y = 30}

[font]
size = 15
normal = {family = "JetBrainsMono Nerd Font Mono", style = "Regular"}
bold = {family = "JetBrainsMono Nerd Font Mono", style = "Bold"}
italic = {family = "JetBrainsMono Nerd Font Mono", style = "Italic"}

[font.offset]
x = 0
y = 1
