import = [
  "~/.config/alacritty/themes/themes/carbonfox.toml",
  "~/.config/alacritty/keybindings.toml",
]
shell = { program = "/opt/homebrew/bin/tmux", args = ["new-session"]}
[env]
TERM = "xterm-256color"
[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
position = { y = 190, x = 150 }
dimensions = { columns = 160, lines = 42}

opacity = 0.9

option_as_alt = "Both"

[font]
normal.family = "DejaVuSansM Nerd Font"
size = 14
