[env]
TERM = "xterm-256color"

[general]
import = ["~/.config/alacritty/themes/rose-pine-moon.toml"]

[window]
decorations = "None"

[font]
size = 18
normal = {family = "JetBrainsMono Nerd Font Mono", style = "Regular"}
bold = {family = "JetBrainsMono Nerd Font Mono", style = "Bold"}
italic = {family = "JetBrainsMono Nerd Font Mono", style = "Italic"}

[font.offset]
x = 0
y = 2
