[keyboard]
bindings = [
    # windows
{ key = "c", mods = "Command", chars = "\u0002\u0063" }, #new window
{ key = "t", mods = "Command", chars = "\u0002\u0074" }, #terminal script
{ key = "d", mods = "Command", chars = "\u0002\u0026" }, #kill window
{ key = "1", mods = "Command", chars = "\u0002\u0031" }, #go to window 1
{ key = "2", mods = "Command", chars = "\u0002\u0032" }, #go to window 2
{ key = "3", mods = "Command", chars = "\u0002\u0033" }, #go to window 3
{ key = "4", mods = "Command", chars = "\u0002\u0034" }, #go to window 4
{ key = "5", mods = "Command", chars = "\u0002\u0035" }, #go to window 5
    # panes
{ key = "\\", mods = "Command", chars = "\u0002\u0025" }, #split vertically
{ key = "-", mods = "Command", chars = "\u0002\u0022" }, #split horizontally 
{ key = "x", mods = "Command", chars = "\u0002\u0078" }, #kill pane
    # others
{ key = "r", mods = "Command", chars = "\u0002\u0072" }, #reload config
{ key = "[", mods = "Command", chars = "\u0002\u005b" }, #vim mode
{ key = "f", mods = "Command", chars = "\u0002\u0066" }, #sessionizer
{ key = "m", mods = "Command", chars = "\u0002\u0064" }, #goes back to default session
    # focus move
{ key = "Right", mods = "Command", chars = "\u0002\u001b\u005b\u0043" }, #focus right pane
{ key = "Left", mods = "Command", chars = "\u0002\u001b\u005b\u0044" }, #focus left pane
{ key = "Up", mods = "Command", chars = "\u0002\u001b\u005b\u0041" }, #focus up pane
{ key = "Down", mods = "Command", chars = "\u0002\u001b\u005b\u0042" }, #focus down pane
]
