gui:
  keybinding:
    universal:
      return: "<enter>"
      prevPage: "k"
      nextPage: "j"
      search: "/"
    main:
      nextItem: "j"
      prevItem: "k"
      search: "/"
      filter: "?"
    files:
      nextItem: "j"
      prevItem: "k"
    branches:
      nextItem: "j"
      prevItem: "k"
    commits:
      nextItem: "j"
      prevItem: "k"
    stash:
      nextItem: "j"
      prevItem: "k"
