#!/usr/bin/env bash

SESSION_NAME=$(tmux display-message -p '#S')

tmux list-windows -t "$SESSION_NAME" \
  -F '#I: #W#{?window_active, (active),} [#{window_panes} panes]' \
  | fzf --reverse --header "Select window (j/k to move, switches immediately)" \
        --bind 'j:down,k:up,down:down,up:up' \
        --bind "change:execute(tmux select-window -t $SESSION_NAME:{1})" \
        --no-select-1 --no-clear
