#!/usr/bin/env bash

export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
  --color=fg:-1,fg+:#53bdfa,bg:-1,bg+:#0b0e14
  --color=hl:#1b3a5b,hl+:#53bdfa,info:#afaf87,marker:#53bdfa
  --color=prompt:#f9af4f,spinner:#7fd962,pointer:#ffffff,header:#c7c7c7
  --color=border:#262626,label:#aeaeae,query:#d9d9d9
  --preview-window="border-rounded" --prompt="" --marker="" --pointer=""
  --separator="─" --scrollbar="" --layout="reverse" --info="right"'

# List sessions
sessions=$(tmux list-sessions -F "#S" 2>/dev/null)

# Use fzf to pick
selected_session=$(echo "$sessions" | fzf --prompt="Search Session:" \
    --bind="ctrl-d:execute(tmux kill-session -t {})+reload(tmux list-sessions -F '#S')")

# If a session is selected
if [ -n "$selected_session" ]; then
    # Switch client to the selected session (cleanly) and exit
    tmux switch-client -t "$selected_session"
fi

# Script ends => popup closes.
