#!/usr/bin/env bash

export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
  --color=fg:-1,fg+:#6e94b2,bg:-1,bg+:#141415
  --color=hl:#333738,hl+:#6e94b2,info:#606079,marker:#6e94b2
  --color=prompt:#f3be7c,spinner:#8cb66d,pointer:#cdcdcd,header:#c3c3d5
  --color=border:#252530,label:#aeaed1,query:#cdcdcd
  --border="rounded" --border-label="" --preview-window="border-rounded" --prompt="$ "
  --marker=">" --pointer="" --separator="─" --scrollbar="│"
  --layout="reverse" --info="right"'

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/work ~/personal -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    # Start a new session and attach
    tmux new-session -s "$selected_name" -c "$selected" -d
    tmux attach -t "$selected_name"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    # Create a new detached session
    tmux new-session -ds "$selected_name" -c "$selected"
fi

# Switch to the new session or open it
tmux switch-client -t "$selected_name"
