set-option -g detach-on-destroy off
set-hook -g session-closed 'if-shell "[[ \"#{session_name}\" != \"default\" ]]" "switch-client -t default"'
set -s escape-time 0
set -g repeat-time 0
set-environment -g PATH "~/.config/tmux:$PATH"

set -ga terminal-overrides ",xterm-256color*:Tc"
set-option -g default-terminal "xterm-256color"

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

unbind c
bind-key c new-window -c "#{pane_current_path}"

unbind '%'
bind '%' split-window -v -c "#{pane_current_path}"  # Vertical split

unbind '"'
bind '"' split-window -h -c "#{pane_current_path}"  # Horizontal split

bind-key -r x kill-pane

bind r source-file ~/.tmux.conf
set -g base-index 1

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy'

bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind-key -r f run-shell "tmux neww tmux-sessionizer"
bind-key -r q run-shell "tmux-kill-windows"
bind-key -r m popup -E "tmux-session-manager"
bind-key -r t run-shell "tmux-terminal"
bind-key -r g run-shell "tmux-git"
bind-key -r s run-shell "tmux-ssh"

# list of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin '2kabhishek/tmux2k'
set -g @tmux2k-theme 'duo'
set -g @tmux2k-duo-bg "#141415"
set -g @tmux2k-icons-only true
set -g @tmux2k-left-plugins "session"
set -g @tmux2k-right-plugins "battery git"
set -g @tmux2k-git-display-status true
set -g @tmux2k-battery-charging-icon " "
set -g @tmux2k-battery-missing-icon " "
set -g @tmux2k-battery-percentage-0 " "
set -g @tmux2k-battery-percentage-1 " "
set -g @tmux2k-battery-percentage-2 " "
set -g @tmux2k-battery-percentage-3 " "
set -g @tmux2k-battery-percentage-4 " "
set -g @tmux2k-prefix-highlight "#f9af4f"

# initialize tmux plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set-option -g pane-border-style 'fg=black'
set-option -g pane-active-border-style 'fg=black'

