#!/bin/bash
TARGET_WINDOW="obsidian"

if tmux select-window -t "$TARGET_WINDOW" 2>/dev/null; then
    tmux select-window -t "$TARGET_WINDOW"
else
    tmux new-window -n "$TARGET_WINDOW"
    # hacky way to ensure the window is closed if obsidian exits
    tmux send-keys -t "$TARGET_WINDOW" "obsidian && exit" Enter
fi
