#!/usr/bin/env bash

export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
  --color=fg:-1,fg+:#6e94b2,bg:-1,bg+:#141415
  --color=hl:#333738,hl+:#6e94b2,info:#606079,marker:#6e94b2
  --color=prompt:#f3be7c,spinner:#8cb66d,pointer:#cdcdcd,header:#c3c3d5
  --color=border:#252530,label:#aeaed1,query:#cdcdcd
  --preview-window="border-rounded" --prompt="" --marker="" --pointer=""
  --separator="─" --scrollbar="" --layout="reverse" --info="right"'

# List sessions
sessions=$(tmux list-sessions -F "#S" 2>/dev/null)

# Use fzf to pick
selected_session=$(echo "$sessions" | fzf --prompt="Search Session:" \
    --bind="ctrl-d:execute(tmux kill-session -t {})+reload(tmux list-sessions -F '#S')")

# If a session is selected
if [ -n "$selected_session" ]; then
    # Switch client to the selected session (cleanly) and exit
    tmux switch-client -t "$selected_session"
fi

# Script ends => popup closes.
