set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",*:Tc"
set -s escape-time 0
set -g repeat-time 0

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

unbind c
bind-key c new-window -c "#{pane_current_path}"

unbind '%'
bind '%' split-window -v -c "#{pane_current_path}"

unbind '"'
bind '"' split-window -h -c "#{pane_current_path}"

bind-key -r x kill-pane

bind r source-file ~/.tmux.conf
set -g base-index 1
set -g renumber-windows on

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy'

bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
bind -r L swap-window -t +1
bind -r H swap-window -t -1

bind-key -r f run-shell "tmux neww ~/.config/tmux/tmux-sessionizer"
bind-key -r s run-shell "tmux-ssh"
bind-key -r d run-shell "tmux-db"

set -g status-position top
set -g status-style 'bg=default,fg=#606060'
set -g status-justify absolute-centre
set -g status-left ''
set -g status-right ''
set -g window-status-format ' #I '
set -g window-status-current-format '#[fg=#cdcdcd,bold] #I '
set -g window-status-separator ''

set -g pane-border-style 'fg=black'
set -g pane-active-border-style 'fg=black'
