set -ga terminal-overrides ",xterm-256color*:Tc"
set-option -g default-terminal "xterm-256color"
set -sg escape-time 0
set-option repeat-time 0

set -g status-style 'bg=default fg=white'
set-option -g pane-border-style 'fg=white'
set-option -g pane-active-border-style 'fg=white'

#instakill panel
bind-key -r x kill-pane

#refresh config
bind r source-file ~/.tmux.conf
set -g base-index 1

#configure vim movement for copy paste
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy'

bind-key -r d switch-client -t default
bind-key -r f run-shell "tmux neww ~/.config/tmux/tmux-sessionizer"

bind-key -r t if-shell 'tmux select-window -t terminal 2>/dev/null' \
        'select-window -t terminal' \
        'new-window -n terminal'
